### ISSUE TITLE
Use google API without billing information requirement

### ISSUE THREAD

**Issue by ilentt** [benshabatnoam/google-translate-vscode-ext#11]
I think your plugin will be more convenience if you using google script instead required user register google api by themself.

These are some solution you should reference

https://ctrlq.org/code/19909-google-translate-api

https://www.proz.com/forum/general_technical_issues/295586-how_to_obtain_a_google_translate_api_v2_key.html

**Comment by benshabatnoam** [comment]
Hi @ilentt , thanks for your kind suggestion. I agree that having the user register google api themselves is inconvenient. I'll take a look at your references.

**Comment by benshabatnoam** [comment]
Hi again @ilentt, I've checked your references, thanks again.

The google api is working I've checked it. But I it looks like I can't use it in this extension because it is not a public api, it is an internal api for google use only, using it is illegal.

I would be happy to hear that I'm mistaken regarding this api, but can you tell me I'm wrong?

**Comment by ilentt** [comment]
Hello @benshabatnoam, I saw that many app and website using google translate script without register google translate api and I think we can do similar them. Here is one of them:
https://gtranslate.io/docs/54-joomla-module-documentation

So for sure we can using it legal we should ask Google Developers Expert who is the author of article above.

Hello @labnol, 
According your article at https://ctrlq.org/code/19909-google-translate-api
Could you please confirm that we can using Google apps script translate in our app or not. If not how can we using it without register google api.

Thank you!

**Comment by benshabatnoam** [comment]
Hello again @ilentt ,

I'm sorry it took forever to answer you about this.
I've looked into this again, and I found that some other extensions are using another free google translate api.

I'm diving into this now hoping to have this change as soon as possible.
