### ISSUE TITLE
Google Translation API issue: Request failed with status code 429

### ISSUE THREAD

**Issue by vtellez** [benshabatnoam/google-translate-vscode-ext#21]
Hello,

First of all, thank you for the great work of this plugin, I find it super useful.

Is there any kind of limitation? After installing the plugin I managed to get some translations to work correctly, but now when trying in any file I receive the error:

"Google Translation API issue: Request failed with status code 429"

**Comment by benshabatnoam** [comment]
Hello @vtellez ,

I'm happy to hear that you're using my extention and you're finding it useful.

The error which you're getting is an error from the google translate library that this extension is using.
I had another issue (#16) regarding this error but the author of it didn't help me to figure out the problem and I wasn't able to reproduce it, at it is working at my end.

Maybe you can give me more details like:
 - you're trying to translate from 'x' language to 'y' language
 - did you try to remove the extension and re-install it again?
 - and basically any information will help. 

If I couldn't reproduce this error regards all of the information you'll give me, we can try [the solution suggested](matheuss/google-translate-api#79) in the base library I've mentioned, then I'll build a fix version and you could test it to see if it works. If it does work than I'll push it to a new official version of the extension.

Thank your for helping this extension,
Noam

**Comment by vtellez** [comment]
Hi @benshabatnoam 

thanks for your answer

I thought it was some limitation on the part of Google, it happens between any language when I do the translation.

I have noticed that the error is given if I try to do many simultaneous translations, 300 or 400 lines at once is usually enough to receive the error.

In this case, once it returns the error, it continues to give it all day. If I try after a day or so it allows me to keep using the translation, but again if I try several hundred lines it returns error 429.

Hope this can help you improve the plugin.

Thank you again for your time

**Comment by benshabatnoam** [comment]
This issue is fixed with new version 2.2.1
Just make sure that you're using the new version.
Let me know if you're still having any problems with new version.

**Comment by vtellez** [comment]
I will try!

Thanks you very much!

**Comment by supriome** [comment]
@benshabatnoam After upgrade to version 2.2.2, There still have error 429, request limit in this plugin.

**Comment by supriome** [comment]
Maybe you should upgrade [vitalets/google-translate-api](https://github.com/vitalets/google-translate-api/tree/master) to version 7.0.0

**Comment by benshabatnoam** [comment]
Hello @supriome thank you for letting me know that.
Can you please help me reproduce this error by telling me how did you reproduce this at your end?
Thanks
