### ISSUE TITLE
Multi cursor translates only one string and removes rest

### ISSUE THREAD

**Issue by Xeevis** [benshabatnoam/google-translate-vscode-ext#24]
https://user-images.githubusercontent.com/5835044/103425158-e009d480-4bb0-11eb-8c21-1afd68242d04.mp4

**Comment by benshabatnoam** [comment]
Thank you @Xeevis for reporting this issue, I'll take a lot at it and do my best to quickly fix this.

**Comment by benshabatnoam** [comment]
I managed to reproduce it easily, 10x @Xeevis

**Comment by Boxiogral** [comment]
Also happening to me

**Comment by benshabatnoam** [comment]
This bug is fixed in v2.2.2
Sorry for the long delay
