### ISSUE TITLE
Replace selected text with translation

### ISSUE THREAD

**Issue by kubawolanin** [benshabatnoam/google-translate-vscode-ext#4]
Hello!

I've just discovered this extension. Great job!
Although, the translated text in a notification window is not very helpful in my use case, as it requires me to highlight and then copy the text, that will eventually be pasted.
How about a feature that would replace currently selected text with translation?

Note that there can be multiple lines of selected text - each one of them should likely be translated separately.

Thank you for your work!

**Comment by meetmicah** [comment]
Don't know @kubawolanin but somehow I discovered the translation on the same day. Could really use this exact feature, though. +1!

**Comment by benshabatnoam** [comment]
10x for the suggested feature, sounds good, I'll implement it in next version.
Regarding your note about multi lines, I'll create a bug for that one.
10x again.

**Comment by benshabatnoam** [comment]
This feature is ready for version 1.2.0

**Comment by kubawolanin** [comment]
Awesome @benshabatnoam! Thanks so much :)
